name: expense_assets
description: Projeto de Ds Assets dedicado ao projeto de Design system
version: 0.4.0+8

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  yaml: ^3.1.0


flutter:
  assets:
    - lib/src/assets/brands/
    - lib/src/assets/icons/
    - lib/src/assets/flags/

